name: Modded Mobs
main: com.themaskedcrusader.moddedmobs.Plugin
version: Alpha 0.1a

commands:
    mobadmin:
        description: Access to all modded mobs admin commands
        usage: /mobadmin [spawn|butcher|help]
        permissions: modded-mobs.admin