faster-zombies:
  enabled: true        # If true: Custom, faster zombies are enabled.
  slow-when-damaged:
    enabled: true      # If true: Faster zombies will get a slowness potion when hit
    duration: 5        # number of seconds for slowness potion to last.

zombies:
  custom-drops:
    enabled: true      # If true, custom zombies drops are configurable. standard zombie drops are disabled
    minimum: 0         # Minimum number of items a zombie can drop
    maximum: 1         # Maximum number of items a zombie can drop
    common-items:      # List of common items in TMC Item Format
      - 367|1
      - 298|1|-1|34
      - 336|1
    rare-chance: 5     # percent chance that item dropped will come from the rare list
    rare-items:        # List of rare items in TMC Item Format
      - 367|1|-1|74
      - 306|1|-1|54
  player-zombies:
    enabled: true      # If true: When a player dies, a zombie will be spawned where they died.
    inventory: true    # If true: Player zombie will carry the inventory of the player who died
  baby-zombies:
    enabled: false     # If true: A percentage of zombie spawned will be turned to baby zombies
    chance: 5          # If enabled, this is the percent of zombies which will be turned to baby zombies.

giants:
  enabled: true          # If true: Custom Giants are enabled
  zombies-on-hit:
    enabled: true        # Spawn a horde of smaller zombies each time the giant is hit
    minimum: 2           # Minimum number of zombies to spawn on hit
    maximum: 4           # Maximum number of zombies to spawn on hit
  explode-on-jump: true  # Cause an explosion when the giant jumps (Not Implemented Yet)

########################################################################################################################
# IMPORTANT!!!  -- THE TMCz ITEM FORMAT --
#
#      <ItemId>|<Quantity>|<Data Value>|<Damage Value>
#
#  Item ID  = The Internal ID of the item. REQUIRED (Consult Minecraft wiki for Item IDs)
#  Quantity = The Quantity of the Item. REQUIRED (Always required, but ignored where noted below)
#  Data     = The Data Value associated with the item. Optional/Required (Consult the Wiki for Appropriate Data values)
#             NOTE: For potions, this value MUST be -1.
#  Damage   = The Damage Value of tha item. Optional. If damage value is specified, then data value MUST also be
#             specified. If you need the damage value, but not the data value, set the data value to  -1.
#             Consult the wiki for appropriate damage values for items, Specifically potions.
#             Potions damage values table: http://www.minecraftwiki.net/wiki/Potions#Data_value_table
#
# EXAMPLE:   373|10|-1|16421  = 10 Splash potions of Instant Healing II
# EXAMPLE:   351|1|10         = 1 piece of lime dye
# EXAMPLE:   276|2            = 2 diamond swords
########################################################################################################################
